final FIXED_FPS : Int = 60;
final FIXED_ITERATIONS : Int = 8;

final PLAYFIELD_PLAYABLE_LEFT : Float = 0.0;
final PLAYFIELD_PLAYABLE_RIGHT : Float = 206.0;
final PLAYFIELD_PLAYABLE_TOP : Float = 0.0;
final PLAYFIELD_PLAYABLE_BOTTOM : Float = 180.0;

final PLAYER_DEFAULT_MOVEMENT_SPEED : Float = 200.0;
final PLAYER_FOCUS_MOVEMENT_SPEED : Float = 90.0;
final PLAYER_HITBOX_RADIUS : Float = 3.0;
final PLAYER_GRAZEBOX_RADIUS : Float = 16.0;
final PLAYER_START_X : Float = 103.0;
final PLAYER_START_Y : Float = 160.0;
final PLAYER_START_HP : Int = 4;

final ENEMY_BASE_X : Float = 103.0;
final ENEMY_BASE_Y : Float = 0.0;